adm/urls.py
from django.urls import path, include

from adm import views

app_name='admin_app'
urlpatterns = [
    # path('', views.index, name='dashboard'),
    path('dashboard/', views.index, name='admin_dashboard'),
    path('dashboard/tickets/', views.tickets, name='admin_tickets'),
    path('dashboard/tickets/create_new_ticket/', views.create_new_ticket, name='create_new_ticket'),
    path('tickets/assign_tickets/<int:pk>', views.assign_tickets, name='assign_tickets'),
    path('dashboard/reports/', views.reports, name='admin_reports'),
    # path('pie-chart/', views.pie_chart, name='pie-chart'),
    path('report-form-chart/', views.report_form_data, name='report-form-chart'),
    path('report-form/', views.report_form, name='report-form'),
]

tkt_mgmt/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('app/', include('app.urls')),
    path('', include('usr.urls')),
    path('dashboard/', include('usr.urls')),
    path('', include('adm.urls')),
    path('dashboard/', include('adm.urls')),
    path('', include('django.contrib.auth.urls')),
    path('dashboard/', include('engineer.urls')),
    path('', include('engineer.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),

]

usr/urls.py
from django.urls import path
from django.conf.urls import url
from usr import views

app_name = "user_tickets"
urlpatterns = [
    path('', views.index, name='dashboard'),
    path('dashboard/', views.index, name='dashboard'),
    path('dashboard/my_tickets/', views.my_tickets, name='my_tickets'),
    path('dashboard/my_tickets/file_a_ticket/', views.file_a_ticket, name='file_a_ticket'),
    path('ticket_details/<int:pk>', views.TicketDetailView.as_view(), name='ticket_details'),
    path('view_history/', views.view_history, name='view_history'),
]

usr/models.py
from django.db import models
from django.contrib import admin
from app.models import Tickets,TicketStatusHistory
from django.forms import inlineformset_factory
# Create your models here.

usr/forms.py
from django import forms
from .models import Tickets
from bootstrap_datepicker_plus import DatePickerInput, TimePickerInput, DateTimePickerInput, MonthPickerInput, YearPickerInput
from bootstrap_modal_forms.forms import BSModalModelForm

class TicketForm(forms.ModelForm):
    class Meta:
        model = Tickets
        fields = ["issue_type", "description", "finish_date", "priority"]
        widgets = {
            'finish_date': DatePickerInput(),
        }
        labels={
            "finish_date":"Required Due By",
        }

class ViewTicketForm(BSModalModelForm):
    class Meta:
        model = Tickets
        fields = ['ticket_id', 'issue_type', "description", "finish_date", "priority", 'assigned_to']

usr/views.py
from app.models import Tickets, TicketStatusHistory
from bootstrap_modal_forms.generic import BSModalReadView
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.db.models import Q
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from app import notification
from .forms import TicketForm
import datetime
# from django.urls import reverse 

# Create your views here.
@login_required(login_url='/login/')
def index(response):
    open_tickets = Tickets.objects.filter((Q(is_closed=None) | Q(is_closed = False)),user=response.user).count()
    closed_tkts = Tickets.objects.filter(is_closed=True,user=response.user).count()
    return render(response, 'usr/dashboard.html',{'new':open_tickets,'complete':closed_tkts})

@login_required(login_url='/login/')
def my_tickets(response):
    open_tickets = Tickets.objects.filter((Q(is_closed=None) | Q(is_closed = False)),user=response.user)
    closed_tkts = Tickets.objects.filter(is_closed=True,user=response.user)
    return render(response, 'usr/tickets.html',{'open_tickets':open_tickets,'closed_tkts':closed_tkts})    

@login_required(login_url='/login/')
def file_a_ticket(response):
    if response.method == "POST":
        form = TicketForm(response.POST or None)
        if form.is_valid():
            tickets = form.save(commit=False)
            tickets.user = response.user
            tickets.created_at = datetime.datetime.now()
            tickets.save()

            notification.email_notification(tickets, True)

            return redirect('/dashboard/my_tickets/')
    else:
        form=TicketForm()
    args = {'form': form}

    return render(response, 'usr/file_a_ticket.html',args)

class TicketDetailView(BSModalReadView):
    model = Tickets
    template_name='usr/ticket_detail.html'

def view_history(request):
    if request.is_ajax and request.method == "GET":
        # get the nick name from the client side.
        pk = request.GET.get("pk", None)
        data = TicketStatusHistory.objects.filter(ticket_id=pk)
        if not data:
            return JsonResponse({'data':'valid'}, status = 400)
        serialized_data = serializers.serialize( "json", data)
        return JsonResponse(serialized_data, status = 200,safe=False)

    return JsonResponse({}, status = 400)

usr/templates/usr/dashboard.html
{% extends base_template_name %}

{% block title %}Dashboard{% endblock %}


{% block content%}
<div class="container">
    <div class="row">
        <div class="col-xl-6 col-sm-6 mb-6 ">
          <div class="card text-white bg-primary o-hidden h-100">
            <div class="card-body">
              <div class="card-body-icon">
                <i class="fa fa-fw fa-plus"></i>
              </div>
              <div class="mr-5">{{new}} Open Tickets!</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="{% url 'user_tickets:my_tickets' %}">
              <span class="float-left">View Details</span>
              <span class="float-right">
                <i class="fa fa-angle-right"></i>
              </span>
            </a>
          </div>
        </div>
        <div class="col-xl-6 col-sm-6 mb-6">
          <div class="card text-white bg-success o-hidden h-100">
            <div class="card-body">
              <div class="card-body-icon">
                <i class="fa fa-fw fa-check"></i>
              </div>
              <div class="mr-5">{{complete}} Closed Tickets!</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="{% url 'user_tickets:my_tickets' %}">
              <span class="float-left">View Details</span>
              <span class="float-right">
                <i class="fa fa-angle-right"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    <div class="row" style="margin-top: 10px;">
        <div class="col col-md-6" id="">
            <h5>Notifications</h5>
            <table class="table">
                <thead class="thead-dark">
                    <th>Title</th>
                    <th>Message</th>
                </thead>
                <tbody id='notification'></tbody>
            </table>
        </div>
      <div class="col col-md-4" id="chart_div">
      </div>
      
    
    </div>
    <div class="row" style="margin-top: 5px;">
        <div class="col col-md-12" id="line_chart_div">
        </div>
    </div>
    </div>
{% endblock %}
{% block js %}

  <script type="text/javascript">
    $(document).ready(function() {
        htmls = '<td colspan="2">There is no new notifications</td>';
        $('#notification').html(htmls);
    });
  </script>
{% endblock %}

usr/templates/usr/file_a_ticket.html
{% extends base_template_name %}
{% load static %}
{% block title %}Create New Ticket{% endblock %}


{% load crispy_forms_tags %}
{% block content%}

<div class="col-md-10">

  <div class="base-title text-center pb-1">
      <h2>Create New Ticket</h2>
  </div>
</div>
<div class="container col-md-6">
  <form method="POST" >
    {% csrf_token %}
  <div class="form-row">
    <div class="form-group  col-md-6">
      {{ form.issue_type|as_crispy_field }}
      {{ form.finish_date|as_crispy_field }}
      {{ form.priority|as_crispy_field }}
    </div>
    <div class="form-group col-md-6">
      {{ form.description|as_crispy_field }}
    </div>
  </div>
  <div class="form-row">
    <div class="form-group  col-md-6">
      <button id="btn_submit" type="submit" class="btn btn-success btn-block"> <i class="fa fa-save" aria-hidden="true"></i>  Create</button>
    </div>
    <div class="form-group col-md-6">
      <a id="btn_cancel" type="button" href="/dashboard/my_tickets" class="btn btn-danger btn-block" style="color: white;"><i class="fa fa-times-circle-o" aria-hidden="true"></i>  Cancel</a>
    </div>
  </div>
</form>
</div>

{% endblock %}
{% block js %}
{{ form.media }} 
<script>
  $(function(){
      $('form').on('submit', function(e){
        let overlay = document.getElementsByClassName('loading-overlay')[0]
        overlay.classList.toggle('is-active');
      });
  })
</script>
{% endblock %}

usr/templates/usr/ticket_detail.html
<div class="modal-header">
  <h3 class="modal-title">Ticket #{{tickets.ticket_id}}: Details</h3>
  <button type="button" class="close" 
    data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <div class="container">
    <div class="row">
      <div class="col-6">
        Issue Type: {{tickets.issue_type}}
      </div>
      <div class="col-6">
        Created By: {{tickets.user.username}}
      </div>
    </div>
    <div class="row">
      <div class="col-6">
        Priority: {{tickets.priority}}
      </div>
      <div class="col-6">
        Phone: {{tickets.user.profile.contact_no}}
      </div>
    </div>
    <div class="row">
      <div class="col-6">
        Due Date: {{tickets.finish_date}}
      </div>
      <div class="col-6">
        Email: {{tickets.user.profile.email}}
      </div>
    </div>
    <div class="row">
      <div class="col-12">Description: {{tickets.description}}</div>
    </div>
    <div class="row">
      <div class="col-12">
        Status History
        <table>
          <thead>
            <th>#</th>
            <th>Date</th>
            <th>Comment</th>
          </thead>
          <tbody id='status_body'>

          </tbody>
        </table>
      </div>
    </div>
  </div>
<div class="modal-footer">
  <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
</div>
<script>
    $(document).ready(function() {
      var tkt_id = "{{ tickets.ticket_id }}"
      $.ajax({
          type: 'GET',
          url: "{% url 'user_tickets:view_history' %}",
          data: {
            'pk': tkt_id
          },
          dataType: 'json',
          success: function (data) {
            datas = JSON.parse(data)
            $('#status_body').html('');
            htmls = '';
            var counter = 1;
            debugger;
            $.each(datas,function(index,item){
              htmls+='<tr><td>'+counter+'</td>';
              date = new Date(item.fields.change_time)
              htmls+='<td>'+date.toDateString()+'</td>';
              switch(item.fields.status){
                case 1:
                  htmls+='<td>Ticket Assigned</td>';
                  break;
                case 2:
                  htmls+='<td>Started working on Ticket</td>';
                  break;
                case 3:
                  htmls+='<td>Ticket Solved</td>';
                  break;
                case 5:
                  htmls+='<td>Ticket Cancelled By User</td>';
                  break;
              }
              htmls+='</tr>';
              counter++;
            });
            $('#status_body').html(htmls);
          }
      });
    });
</script>

usr/templates/usr/tickets.html
{% extends base_template_name %}
{% load static %}
{% block title %}Tickets{% endblock %}

{% block style %}
<link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet">

{% endblock %}
{% block content%}
{% include "app/_modal.html" %}
{% include "app/chat.html" %}
<div class="container">
    <div class="row">
          <div class="col col-md-4">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                  <a class="nav-link active" data-toggle="tab" href="#new">Open Tickets</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#closed">Closed Tickets</a>
                </li>
                </ul>
        </div>
        <div class="col col-md-3 base-title text-center pb-1">
            <h2>Tickets list</h2>
        </div>
          <div class="col col-md-3 offset-md-2 ">
            <a type="button" href="/dashboard/my_tickets/file_a_ticket" class="btn btn-success btn-block" style="color: white;"><i class="fa fa-plus" aria-hidden="true"></i>  Create New Ticket</a>

          </div>
    
    </div>

    <hr />
    
    <!-- Tab panes -->
    <div class="tab-content">
        <div class="tab-pane container active" id="new">
            <table  id="example" class="table table-striped table-bordered tkt_tbl" style="width:100%">
                <thead>
                    <tr>
                        <th>Ticket No.</th>
                        <th>Issue</th>
                        <th>Due Date</th>
                        <th>Priority</th>
                        <th>Created At</th>
                        <th>Status</th>
                        <th>Assigned To</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in open_tickets %}
                    <tr style="background-color: {% if item.is_past_due %}red{%endif%};">
                        <td data-order="{{ item.ticket_id }}">#{{ item.ticket_id }} </td>
                        <td>{{ item.issue_type }} </td>
                        <td>{{ item.finish_date|date:'Y-m-d' }} </td>
                        <td style="background-color: {{item.priority_color}};" data-order="{{ item.priority_order }}">{{ item.priority }} </td>
                        <td>{{ item.created_at|date:'Y-m-d H:i' }} </td>
                        <td> {% if item.status %}
                            {{ item.status.status }}
                        {% else %}
                            Pending
                        {% endif %}</td>
                        <td>{{ item.assigned_to.username }} </td>
                        <td>
                            <a type="button" data-id="{% url 'user_tickets:ticket_details' item.ticket_id %}" class="viewtkt btn btn-primary"> <i class="fa fa-eye" aria-hidden="true"></i>  </a>
                            <a type="button" data-toggle="modal" data-id="{{ item.ticket_id }}" data-target="#chatModal" class="chat btn btn-success"> <i class="fa fa-comments" aria-hidden="true"></i>  </a>
                        </td>
                    </tr>
                        {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="tab-pane container fade" id="closed">
            <table  id="example" class="table table-striped table-bordered tkt_tbl" style="width:100%">
                <thead>
                    <tr>
                        <th>Ticket No.</th>
                        <th>Issue</th>
                        <th>Due Date</th>
                        <th>Priority</th>
                        <th>Created At</th>
                        <th>Status</th>
                        <th>Assigned To</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in closed_tkts %}
                    <tr>
                        <td data-order="{{ item.ticket_id }}">#{{ item.ticket_id }} </td>
                        <td>{{ item.issue_type }} </td>
                        <td>{{ item.finish_date|date:'Y-m-d' }} </td>
                        <td style="background-color: {{item.priority_color}};" data-order="{{ item.priority_order }}">{{ item.priority }} </td>
                        <td>{{ item.created_at|date:'Y-m-d H:i' }} </td>
                        <td> {% if item.status %}
                            {{ item.status.status }}
                        {% else %}
                            Pending
                        {% endif %}</td>
                        <td>{{ item.assigned_to.username }} </td>
                        <td>
                            <a type="button" data-id="{% url 'user_tickets:ticket_details' item.ticket_id %}" class="viewtkt btn btn-primary"> <i class="fa fa-eye" aria-hidden="true"></i>  </a>
                        </td>

                    </tr>
                        {% endfor %}
                </tbody>
            </table>

        </div>
</div>
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>
{% endblock %}

{% block js %}

<script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>
<script src="{% static 'js/chat.js' %}"></script>
<script>
    $(document).ready(function() {
        $('.tkt_tbl').DataTable();
        $('.viewtkt').click(function(){
            $(this).modalForm({
                formURL: $(this).data('id')
            });
        });
    } );
    
</script>
{% endblock %}

usr/templates/usr/usr_dash.html
{% extends "app/dash_base.html" %}

{% block sidnav %}
<li>
    <a href="/dashboard/my_tickets">
      <i class="fa fa-ticket" aria-hidden="true"></i> Tickets
    </a>
  </li>
{% endblock %}