accounts/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('register_engineer/', views.register_user_by_admin, name='register_engineer'),
    path('updateprofile/<int:pk>', views.update_profile, name ='updateprofile'),
    path('password/', views.change_password, name='change_password'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]

adm/urls.py
from django.urls import path, include

from adm import views

app_name='admin_app'
urlpatterns = [
    # path('', views.index, name='dashboard'),
    path('dashboard/', views.index, name='admin_dashboard'),
    path('dashboard/tickets/', views.tickets, name='admin_tickets'),
    path('dashboard/tickets/create_new_ticket/', views.create_new_ticket, name='create_new_ticket'),
    path('tickets/assign_tickets/<int:pk>', views.assign_tickets, name='assign_tickets'),
    path('dashboard/reports/', views.reports, name='admin_reports'),
    # path('pie-chart/', views.pie_chart, name='pie-chart'),
    path('report-form-chart/', views.report_form_data, name='report-form-chart'),
    path('report-form/', views.report_form, name='report-form'),
]

engineer/urls.py
from django.urls import path

from engineer import views

app_name = "engineer_app"
urlpatterns = [
    path('', views.index, name='dashboard'),
    path('dashboard/', views.index, name='dashboard'),
    path('dashboard/ticket_list/', views.ticket_list, name='eng_ticket_list'),
    path('confirmation/', views.start_working, name='start_working_confirm'),
    path('confirmation/close_tkt', views.close_ticket, name='close_ticket'),
    path('confirmation/take_tkt', views.take_ticket, name='take_ticket'),
    path('dashboard/engineers_list', views.engineers_list, name='engineers_list'),
    path('change_active_status/<int:pk>', views.change_active_status, name='change_active_status'),
    path('report-form-chart-eng/', views.report_form_data_eng, name='report-form-chart-eng'),
]

tkt_mgmt/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('app/', include('app.urls')),
    path('', include('usr.urls')),
    path('dashboard/', include('usr.urls')),
    path('', include('adm.urls')),
    path('dashboard/', include('adm.urls')),
    path('', include('django.contrib.auth.urls')),
    path('dashboard/', include('engineer.urls')),
    path('', include('engineer.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),

]

usr/urls.py
from django.urls import path
from django.conf.urls import url
from usr import views

app_name = "user_tickets"
urlpatterns = [
    path('', views.index, name='dashboard'),
    path('dashboard/', views.index, name='dashboard'),
    path('dashboard/my_tickets/', views.my_tickets, name='my_tickets'),
    path('dashboard/my_tickets/file_a_ticket/', views.file_a_ticket, name='file_a_ticket'),
    path('ticket_details/<int:pk>', views.TicketDetailView.as_view(), name='ticket_details'),
    path('view_history/', views.view_history, name='view_history'),
]

engineer/forms.py
from django import forms
from bootstrap_datepicker_plus import DatePickerInput, TimePickerInput, DateTimePickerInput, MonthPickerInput, YearPickerInput

# form for report
import datetime
class ReportFormEng(forms.Form):
    # username = forms.CharField(label="Username", max_length=100)
    date_from = forms.DateTimeField(initial=datetime.date.today().replace(day=1), widget=DatePickerInput(format='%m/%d/%Y'))
    date_to = forms.DateTimeField(initial=datetime.date.today, widget=DatePickerInput(format='%m/%d/%Y'))

engineer/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from app.models import Tickets,Status, TicketStatusHistory
from app import notification
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.db.models import Q
import datetime
from accounts.decorators import allowed_user

# Create your views here.
@login_required(login_url='/login/')
def index(response):
    assined_status = status=Status.objects.get(status='Assigned')
    inprogress_status = status=Status.objects.get(status='Inprogress')
    new_tickets = Tickets.objects.filter(status=Status.objects.get(status='Assigned'),assigned_to=response.user).count()
    overdue = Tickets.objects.filter((Q(status=assined_status) | Q(status = inprogress_status)), finish_date__lt = datetime.datetime.today(),assigned_to=response.user).count()
    complete = Tickets.objects.filter(status=Status.objects.get(status='Complete'),assigned_to=response.user).count()

    return render(response, 'engineer/dashboard.html',{'new':new_tickets,'overdue':overdue,'complete':complete})

@login_required(login_url='/login/')
def ticket_list(response):
    new_tickets = Tickets.objects.filter(status=Status.objects.get(status='Assigned'),assigned_to=response.user)
    working_on = Tickets.objects.filter(status=Status.objects.get(status='Inprogress'),assigned_to=response.user)
    complete = Tickets.objects.filter(status=Status.objects.get(status='Complete'),assigned_to=response.user)
    unassigned = Tickets.objects.filter(status=None,assigned_to=None)

    args = {
        'new_tickets':new_tickets,
        'working_on':working_on,
        'complete':complete,
        'unassigned':unassigned
    }
    return render(response, 'engineer/tickets_list.html',args)


def start_working(request):
    if request.is_ajax and request.method == "GET":
        # get the nick name from the client side.
        pk = request.GET.get("pk", None)
        ticket = Tickets.objects.filter(ticket_id=pk).first()
        ticket.status = Status.objects.get(status='Inprogress')
        ticket.save()
        notification.change_status(ticket,request.user,'Started Working on Ticket')

        return JsonResponse({'data': 'success'}, status = 200)

    return JsonResponse({}, status = 400)


def close_ticket(request):
    if request.is_ajax and request.method == "GET":
        # get the nick name from the client side.
        pk = request.GET.get("pk", None)
        comment = request.GET.get("comment", None)
        ticket = Tickets.objects.filter(ticket_id=pk).first()
        ticket.status = Status.objects.get(status='Complete')
        ticket.is_closed = True
        ticket.save()
        notification.change_status(ticket,request.user,('Ticket has been successfully closed.' if comment == '' else comment))

        return JsonResponse({'data': 'success'}, status = 200)

    return JsonResponse({}, status = 400)

@login_required(login_url='/login/')
def engineers_list(response):
    active_engineers = User.objects.filter(groups__name='engineer', is_active=True)
    inactive_engineers = User.objects.filter(groups__name='engineer', is_active=False)

    args = {
        'active_engineers': active_engineers,
        'inactive_engineers': inactive_engineers
    }
    return render(response, 'engineer/engineers_list.html', args)

def take_ticket(request):
    if request.is_ajax and request.method == "GET":
        # get the nick name from the client side.
        pk = request.GET.get("pk", None)
        comment = request.GET.get("comment", None)
        ticket = Tickets.objects.filter(ticket_id=pk).first()
        ticket.assigned_to = request.user
        ticket.assigned_at = datetime.datetime.now()
        ticket.status = Status.objects.get(status='Assigned')
        ticket.is_closed = False
        ticket.save()
        notification.change_status(ticket,request.user,('Ticket has been successfully Assigned.' if comment == '' else comment))

        return JsonResponse({'data': 'success'}, status = 200)

    return JsonResponse({}, status = 400)

@allowed_user(allowed_roles=['admin'])
def change_active_status(request, pk):
    user = get_object_or_404(User, pk=pk)
    if user.is_active == True:
        user.is_active = False
    elif user.is_active == False:
        user.is_active = True
    user.save()
    return redirect('/dashboard/engineers_list')

# for report form
from .forms import ReportFormEng

def report_form_data_eng(request):
    user_group = [group.name for group in request.user.groups.all()]

    if request.method == 'POST':
        form = ReportFormEng(request.POST)
        if form.is_valid():
            # username = form.cleaned_data['username']
            date_from = form.cleaned_data['date_from']
            date_to = form.cleaned_data['date_to']
            # print(username, date_from, date_to)
            # print(type(date_from))

            labels = ["Completed", "In Progress", "Overdue"]
            data = []
            if 'admin' in user_group:
                engineer_id = User.objects.get(username=username).id
            elif 'engineer' in user_group:
                engineer_id = request.user.id
            else:
                print("not accessible")

            queryset = Tickets.objects.filter(assigned_to__exact=engineer_id)

            complete_queryset = queryset.filter(status__status='Complete')
            no_of_completed_tickets = find_no(complete_queryset, date_from, date_to)
            print("no of completed tickets", no_of_completed_tickets)
            data.append(no_of_completed_tickets)

            inprogress_queryset = queryset.filter(status__status='Inprogress')
            no_of_inprogress_tickets = find_no(inprogress_queryset, date_from, date_to)
            print("no of inprogress tickets", no_of_inprogress_tickets)
            data.append(no_of_inprogress_tickets)

            overdue_queryset = queryset.filter(status__status='Inprogress')
            no_of_overdue_tickets = find_overdue_no(overdue_queryset, date_from, date_to)
            print("no of overdue tickets", no_of_overdue_tickets)
            data.append(no_of_overdue_tickets)

            return render(request, 'engineer/pie_chart_eng.html', {
                'labels': labels,
                'data': data,
    })

    else:
        form = ReportFormEng()
    if 'admin' in user_group:
        return render(request, 'adm/report_form.html', {'form': form})
    else:
        return render(request, 'engineer/report_form_eng.html', {'form': form})


def find_no(queryset, date_from, date_to):
    ticket_ids = [tkt_id.pk for tkt_id in queryset]
    count = 0
    for ticket_id in ticket_ids:
        match_val = TicketStatusHistory.objects.filter(ticket_id=ticket_id)
        match_val = match_val.order_by('-change_time')[0]
        if date_from <= match_val.change_time and match_val.change_time <= date_to:
            count = count + 1
    return count

def find_overdue_no(queryset, date_from, date_to):
    ticket_ids = [tkt_id.pk for tkt_id in queryset]
    count = 0
    for ticket_id in ticket_ids:
        match_val = TicketStatusHistory.objects.filter(ticket_id=ticket_id)
        match_val = match_val.order_by('-change_time')[0]
        finish_date = Tickets.objects.get(pk=ticket_id).finish_date
        if date_from <= match_val.change_time and match_val.change_time <= date_to and finish_date < datetime.date.today():
            count = count + 1
    return count

engineer/templates/engineer/eng_sidenav.html
{% extends "app/dash_base.html" %}

{% block sidnav %}
<li>
    <a href="\dashboard\ticket_list">
      <i class="fa fa-ticket" aria-hidden="true"></i> Tickets
      <span class="caret"></span>
    </a>

  </li>
  <li>
    <a href="\dashboard\report-form-chart-eng">
      <i class="fa fa-ticket" aria-hidden="true"></i> Reports
      <span class="caret"></span>
    </a>

  </li>
{% endblock %}

engineer/templates/engineer/engineers_list.html
{% extends base_template_name %}

{% block title %}Engineers{% endblock %}

{% block style %}
    <link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet">
{% endblock %}


{% block content%}
    <div class="container">
        <div class="row">
            <div class="col">
                <h3>Engineers list</h3>
            </div>
            <div class="col col-md-3 offset-md-2">
                <a type="button" href="{% url 'accounts:register_engineer' %}" class="btn btn-success btn-block" style="color: white;"><i class="fa fa-plus" aria-hidden="true"></i>  Create New Engineer</a>
            </div>
        </div>

        <div class="row">
            <div class="col col-md-8">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#active">Active Engineers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#inactive">Inactive Engineers</a>
                    </li>
                </ul>
            </div>
        </div>
        
        <hr />
        <div class="tab-content">
            <div class="tab-pane container active" id="active">
                <table id="active_engineers" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Username</th>
                            <th>Email</th>
                            <th>Contact No</th>
                            <th>Address</th>
                            <th>Change Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for engineer in active_engineers %}
                            <tr>
                                <td>{{ engineer.first_name }}</td>
                                <td>{{ engineer.last_name }}</td>
                                <td>{{ engineer.username }}</td>
                                <td>{{ engineer.email }}</td>
                                <td>{{ engineer.profile.contact_no }}</td>
                                <td>{{ engineer.profile.address }}</td>
                                <td><a type="button" href="{% url 'engineer_app:change_active_status' pk=engineer.id %}" class="viewtkt btn btn-primary"> <i class="fa fa-caret-down" aria-hidden="true"></i>  </a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="tab-pane container fade" id="inactive">
                <table id="inactive_engineers" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Username</th>
                            <th>Email</th>
                            <th>Contact No</th>
                            <th>Address</th>
                            <td>Change Status</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for engineer in inactive_engineers %}
                            <tr>
                                <td>{{ engineer.first_name }}</td>
                                <td>{{ engineer.last_name }}</td>
                                <td>{{ engineer.username }}</td>
                                <td>{{ engineer.email }}</td>
                                <td>{{ engineer.profile.contact_no }}</td>
                                <td>{{ engineer.profile.address }}</td>
                                <td><a type="button" href="{% url 'engineer_app:change_active_status' pk=engineer.id %}" class="viewtkt btn btn-primary"> <i class="fa fa-caret-up" aria-hidden="true"></i>  </a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#active_engineers').DataTable();
            $('#inactive_engineers').DataTable();
        } );

    </script>
{% endblock %}

engineer/templates/engineer/pie_chart_eng.html
{% extends base_template_name %}

{% block content  %}
    <div id="container" style="width: 75%;">
      <div class="row">
        <p style="margin-left: 250px;">Report for: <b>{{ request.user.username }} </b></p>
      </div>  
      <div class="row">
        <canvas id="pie-chart"></canvas>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script>

        var config = {
          type: 'pie',
          data: {
            datasets: [{
              data: {{ data|safe }},
              backgroundColor: [
                '#696969', '#808080', '#A9A9A9', '#C0C0C0', '#D3D3D3'
              ],
              label: 'Population'
            }],
            labels: {{ labels|safe }}
          },
          options: {
            responsive: true
          }
        };
    
        window.onload = function() {
          var ctx = document.getElementById('pie-chart').getContext('2d');
          window.myPie = new Chart(ctx, config);
        };
    
      </script>

{% endblock %}

engineer/templates/engineer/report_form_eng.html
{% extends base_template_name %}
{% load bootstrap4 %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Generate Report" class="btn btn-primary btn-block">
    </form>
{% endblock %}

{% block js %}
    {{ form.media }} 
{% endblock %}

engineer/templates/engineer/tickets_list.html
{% extends base_template_name %}
{% load static %}
{% block title %}Tickets{% endblock %}

{% block style %}
<link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet">

{% endblock %}


{% block content%}

{% include "app/_modal.html" %}
{% include "app/confirmation.html" %}
{% include "app/chat.html" %}
<div class="container">
    <div class="row">
        <div class="col col-md-8">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                  <a class="nav-link active" data-toggle="tab" href="#new">New Tickets</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#working">Working On</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#complete">Complete</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#unassigned">Unassigned Tickets</a>
                </li>
                </ul>
        </div>
        <div class="col">
            <h3>Tickets list</h3>
          </div>
          <!-- <div class="col col-lg-3">
            <a type="button" href="/dashboard/tickets/create_new_ticket" class="btn btn-success btn-block" style="color: white;"><i class="fa fa-plus" aria-hidden="true"></i>  Create New Ticket</a>

          </div> -->
    
    </div>
<!-- Modal -->
    <hr />
    
    <!-- Nav tabs -->
    
    
    <!-- Tab panes -->
    <div class="tab-content">
        <div class="tab-pane container active" id="new">
            <table  id="example" class="table table-striped table-bordered tkt_tbl" style="width:100%">
                <thead>
                    <tr>
                        <th>Ticket No.</th>
                        <th>Issue</th>
                        <th>Issued By</th>
                        <th>Due Date</th>
                        <th>Created At</th>
                        <th>Status</th>
                        <th>Priority</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in new_tickets %}
                <tr style="background-color: {% if item.is_past_due %}red{%endif%};">
                        <td data-order="{{ item.ticket_id }}">#{{ item.ticket_id }} </td>
                        <td>{{ item.issue_type }} </td>
                        <td>{{ item.user.username }} </td>
                        <td>{{ item.finish_date|date:'Y-m-d' }} </td>
                        <td>{{ item.created_at|date:'Y-m-d H:i' }} </td>
                        <td>
                            {{ item.status.status }}
                        </td>
                        <td style="background-color: {{item.priority_color}};" data-order="{{ item.priority_order }}">{{ item.priority }} </td>
                        <td>
                            <a type="button" data-id="{% url 'user_tickets:ticket_details' item.ticket_id %}" class="viewtkt btn btn-primary"> <i class="fa fa-eye" aria-hidden="true"></i>  </a>
                            <a type="button" data-toggle="modal" data-id="{{ item.ticket_id }}" data-target="#confirmationModal" class="start_working btn btn-success"> <i class="fa fa-play-circle" aria-hidden="true"></i>  </a>
                            <a type="button" data-toggle="modal" data-id="{{ item.ticket_id }}" data-target="#chatModal" class="chat btn btn-success"> <i class="fa fa-comments" aria-hidden="true"></i>  </a>
                        </td>
                    </tr>
                        {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="tab-pane container fade" id="working">
            <table  id="working_tbl" class="table table-striped table-bordered tkt_tbl" style="width:100%">
                <thead>
                    <tr>
                        <th>Ticket No.</th>
                        <th>Issue</th>
                        <th>Issued By</th>
                        <th>Due Date</th>
                        <th>Created At</th>
                        <th>Status</th>
                        <th>Priority</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in working_on %}
                    <tr style="background-color: {% if item.is_past_due %}red{%endif%};">
                        <td data-order="{{ item.ticket_id }}">#{{ item.ticket_id }} </td>
                        <td>{{ item.issue_type }} </td>
                        <td>{{ item.user.username }} </td>
                        <td>{{ item.finish_date|date:'Y-m-d' }} </td>
                        <td>{{ item.created_a|date:'Y-m-d H:i' }} </td>
                        <td>
                            {{ item.status.status }}
                        </td>
                        <td style="background-color: {{item.priority_color}};" data-order="{{ item.priority_order }}">{{ item.priority }} </td>
                        <td>
                            <a type="button" data-id="{% url 'user_tickets:ticket_details' item.ticket_id %}" class="viewtkt btn btn-primary"> <i class="fa fa-eye" aria-hidden="true"></i>  </a>
                            <a type="button" data-toggle="modal" data-id="{{ item.ticket_id }}" data-target="#confirmationModal" class="close_tkt btn btn-success"> <i class="fa fa-play-circle" aria-hidden="true"></i>  </a>
                            <a type="button" data-toggle="modal" data-id="{{ item.ticket_id }}" data-target="#chatModal" class="chat btn btn-success"> <i class="fa fa-comments" aria-hidden="true"></i>  </a>
                        </td>
                    </tr>
                        {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="tab-pane container fade" id="complete">
            <table  id="complete_tbl" class="table table-striped table-bordered tkt_tbl" style="width:100%">
                <thead>
                    <tr>
                        <th>Ticket No.</th>
                        <th>Issue</th>
                        <th>Issued By</th>
                        <th>Due Date</th>
                        <th>Created At</th>
                        <th>Status</th>
                        <th>Priority</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in complete %}
                    <tr>
                        <td data-order="{{ item.ticket_id }}">#{{ item.ticket_id }} </td>
                        <td>{{ item.issue_type }} </td>
                        <td>{{ item.user.username }} </td>
                        <td>{{ item.finish_date|date:'Y-m-d' }} </td>
                        <td>{{ item.created_at|date:'Y-m-d H:i' }} </td>
                        <td>
                            {{ item.status.status }}
                        </td>
                        <td style="background-color: {{item.priority_color}};" data-order="{{ item.priority_order }}">{{ item.priority }} </td>
                        <td>
                            <a type="button" data-id="{% url 'user_tickets:ticket_details' item.ticket_id %}" class="viewtkt btn btn-primary"> <i class="fa fa-eye" aria-hidden="true"></i>  </a>
                        </td>
                    </tr>
                        {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="tab-pane container fade" id="unassigned">
            <table  id="unassigned_tbl" class="table table-striped table-bordered tkt_tbl" style="width:100%">
                <thead>
                    <tr>
                        <th>Ticket No.</th>
                        <th>Issue</th>
                        <th>Issued By</th>
                        <th>Due Date</th>
                        <th>Created At</th>
                        <th>Status</th>
                        <th data-order="{% if item.priority == 'urgent' %} {{1}} {%elif item.priority == 'high'%}{{2}}{%elif item.priority == 'medium'%}{{3}}{%else%}{{4}}{%endif%}">Priority</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in unassigned %}
                    <tr style="background-color: {% if item.is_past_due %}red{%endif%};">
                        <td data-order="{{ item.ticket_id }}">#{{ item.ticket_id }} </td>
                        <td>{{ item.issue_type }} </td>
                        <td>{{ item.user.username }} </td>
                        <td>{{ item.finish_date|date:'Y-m-d' }} </td>
                        <td>{{ item.created_at|date:'Y-m-d H:i' }} </td>
                        <td>
                            {{ item.status.status }}
                        </td>
                        <td style="background-color: {{item.priority_color}};" data-order="{{ item.priority_order }}">{{ item.priority }} </td>
                        <td>
                            <a type="button" data-id="{% url 'user_tickets:ticket_details' item.ticket_id %}" class="viewtkt btn btn-primary"> <i class="fa fa-eye" aria-hidden="true"></i>  </a>
                            <a type="button" data-toggle="modal" data-id="{{ item.ticket_id }}" data-target="#confirmationModal" class="take_tkt btn btn-success"> <i class="fa fa-thumb-tack" aria-hidden="true"></i>  </a>
                            <a type="button" data-toggle="modal" data-id="{{ item.ticket_id }}" data-target="#chatModal" class="chat btn btn-success"> <i class="fa fa-comments" aria-hidden="true"></i>  </a>
                        </td>
                    </tr>
                        {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    
</div>

{% endblock %}

{% block js %}
<script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>
<script src="{% static 'js/chat.js' %}"></script>
<script>
    $(document).ready(function() {
        $('.tkt_tbl').DataTable();
        $('.viewtkt').on('click', function(){
            $(this).modalForm({
                formURL: $(this).data('id')
            });
        });
        $('#confirmationModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget) // Button that triggered the modal
            ticket_id = parseInt( button.data('id'));
            var modal = $(this)
            modal.find('.modal-title').text('Ticket #' + ticket_id)
            var confirm_url;
            var args;
            var alert_message;
            if(button.hasClass('start_working')){
                modal.find('.modal-body').text('Do you want to start working on Issue #'+ ticket_id + '?')
                confirm_url = "{% url 'engineer_app:start_working_confirm' %}";
                alert_message='Ticket status successfully changed.'
                
            } else if (button.hasClass('close_tkt')) {
                html = '';
                html += '<h6>Have you solved the Issue?</h6>';
                html += '<form><textarea id="close_comment" class="form-control" placeholder="Type your comment for future references... (optional)" ></textarea>';
                modal.find('.modal-body').html(html)
                
                confirm_url = "{% url 'engineer_app:close_ticket' %}";
                alert_message='Ticket successfully closed.'
                
            } else if (button.hasClass('take_tkt')) {
                html = '';
                html += 'Do you want to assign the ticket to yourself?';
                modal.find('.modal-body').html(html)
                
                confirm_url = "{% url 'engineer_app:take_ticket' %}";
                alert_message='Ticket successfully Taken.'
                
            }
           
            $('#btn_confirm').off('click').one('click', function(){
                $('#confirmationModal').modal('hide');
                let overlay = document.getElementsByClassName('loading-overlay')[0]
                overlay.classList.toggle('is-active');  
                if(button.hasClass('close_tkt')){
                    args = {
                        'pk': ticket_id,
                        'comment': $('#close_comment').val()
                    }
                } else{
                    args = {
                        'pk': ticket_id,
                    }
                }
                debugger
                $.ajax({
                    type: 'GET',
                    url: confirm_url,
                    data: args,
                    dataType: 'json',
                    success: function (data) {
                        alert(alert_message);
                        document.location.href ="{% url 'engineer_app:eng_ticket_list' %}";
                    }
                });
            });
        });
    });

</script>
{% endblock %}