accounts/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('register_engineer/', views.register_user_by_admin, name='register_engineer'),
    path('updateprofile/<int:pk>', views.update_profile, name ='updateprofile'),
    path('password/', views.change_password, name='change_password'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]

adm/urls.py
from django.urls import path, include

from adm import views

app_name='admin_app'
urlpatterns = [
    # path('', views.index, name='dashboard'),
    path('dashboard/', views.index, name='admin_dashboard'),
    path('dashboard/tickets/', views.tickets, name='admin_tickets'),
    path('dashboard/tickets/create_new_ticket/', views.create_new_ticket, name='create_new_ticket'),
    path('tickets/assign_tickets/<int:pk>', views.assign_tickets, name='assign_tickets'),
    path('dashboard/reports/', views.reports, name='admin_reports'),
    # path('pie-chart/', views.pie_chart, name='pie-chart'),
    path('report-form-chart/', views.report_form_data, name='report-form-chart'),
    path('report-form/', views.report_form, name='report-form'),
]

tkt_mgmt/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('app/', include('app.urls')),
    path('', include('usr.urls')),
    path('dashboard/', include('usr.urls')),
    path('', include('adm.urls')),
    path('dashboard/', include('adm.urls')),
    path('', include('django.contrib.auth.urls')),
    path('dashboard/', include('engineer.urls')),
    path('', include('engineer.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),

]

app/templates/app/_modal.html
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>

app/templates/app/base.html
{% load static %}

{% load bootstrap4 %}
{% bootstrap_javascript jquery='full' %}

<!doctype html>
<html>
    <head>
        <link rel="stylesheet" href="{% static "app/css/main.css" %}" >
        <link rel="stylesheet" href="{% static "app/css/loading_spinner.css" %}" >
        {% block dash_style %}{% endblock %}
        {% block style %}{% endblock %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
         <!-- Bootstrap CSS -->
        <link rel="icon" type="image/png" href="{% static "app/images/favicon.ico" %}"/>
        <title>{% block title %}Arif Systems{% endblock %}</title>
        {% bootstrap_css %}
    </head>

    <body>
        
        <div class="loading-overlay">
            <div id="loading-bar-spinner"class="spinner"><div class="spinner-icon"></div></div>
          </div>
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #e3f2fd;">
            <div class="d-flex flex-grow-1">
                <span class="w-100 d-lg-none d-block"><!-- hidden spacer to center brand on mobile --></span>
                <a class="navbar-brand d-none d-lg-inline-block" href="{% if user.is_authenticated %}/dashboard{% else %}/{% endif %}">
                    <img src="{% static "app/images/logo.png" %}" width="200" height="40" class="d-inline-block align-top" alt="logo">
                </a>
                <div class="w-100 text-right">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#myNavbar">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
            </div>
            <div class="collapse navbar-collapse flex-grow-1 text-right" id="myNavbar">
                <ul class="navbar-nav ml-auto flex-nowrap">
                    <li class="nav-item">
                        <a href="/" class="nav-link m-2 menu-item nav-active">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="/faq" class="nav-link m-2 menu-item">FAQs</a>
                    </li>

                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a href="/dashboard" class="nav-link m-2 menu-item">Dashboard</a>
                        </li>
                        <li class="nav-item dropdown active">
                            <a class="nav-link m-2 menu-item dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ user.username }}
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'accounts:updateprofile' pk=user.profile.id %}">Update Profile</a>
                                <a class="dropdown-item" href="{% url 'accounts:change_password' %}">Change Password</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                            </div>
                        </li>
                    
                    {% else %}
                        <li class="nav-item">
                            <a href="{% url 'accounts:login' %}" class="nav-link m-2 menu-item">Login</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'accounts:signup' %}" class="nav-link m-2 menu-item">Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        {% block dash_nav %}
        {% endblock %}
        {% block header %}
        {% endblock %}
        <div class="content-container">
            
            <div class="container-fluid">
          
              <!-- Main component for a primary marketing message or call to action -->
              <div class="jumbotron">
                <div id="content" name="content" class="main container">
                    <div class="row justify-content-center">
                        {% block content %}
                        {% endblock %}
                    </div>
              </div>
          
            </div>
          </div>
 
  <!-- Footer -->
  <footer class="py-3 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Arif Systems - Online Complaint Management</p>
    </div>
    <!-- /.container -->
  </footer>
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
<script>
    $(function(){
        // $('#loading-bar-spinner').hide();
    })
</script>
        {% block dash_js %}
        {% endblock %}
        {% block js %}
        {% endblock %}

    </body>
</html>

app/templates/app/chat.html
<div class="modal fade" id="chatModal" tabindex="-1" role="dialog" aria-labelledby="chatModalTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        
        <div class="modal-header">
          <h5 class="modal-title" id="chatModalTitle">Chat</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="chat-box bg-white overflow-auto" style="height: 50vh;">
    
          </div>
        </div>
        <div class="modal-footer">
            <div class="input-group" style="width: 100%;">
              <input id='message' type="text" required placeholder="Type a message" aria-describedby="btn_send" class="form-control rounded-0 border-0 py-4 bg-light">
              <div class="input-group-append">
                <button id="btn_send" class="btn btn-link"> <i class="fa fa-paper-plane"></i></button>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>

app/templates/app/confirmation.html
<div class="modal fade" id="confirmationModal" tabindex="-1" role="dialog" aria-labelledby="confirmationModalTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        
        <div class="modal-header">
          <h5 class="modal-title" id="confirmationModalTitle">Confirmation</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
          <button type="button" id='btn_confirm' class="btn btn-success">Yes</button>
        </div>
      </div>
    </div>
  </div>

app/templates/app/dash_base.html
{% extends 'app/base.html' %}
{% load static %}

{% block dash_style %}
<link rel="stylesheet" href="{% static "app/css/dash_base.css" %}" >
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
{% endblock %}


{% block dash_nav %}
  <div class="sidebar-container" >
    <div class="sidebar-logo">
        Welcome,  {{ user.username }}
        {{ user.groups.group__name }}
    </div>
    <ul class="sidebar-navigation">
      <li class="header">Site Navigation</li>
      <li>
        <a href="/dashboard/">
          <i class="fa fa-home" aria-hidden="true"></i> Dashboard
        </a>
      </li>
      {% block sidnav %}{% endblock %}
      <li>
        <a href="#">
          <i class="fa fa-info-circle" aria-hidden="true"></i> Information
        </a>
      </li>
      <li class="header">User Navigation</li>
      <li>
        <a href="{% url 'accounts:updateprofile' pk=user.profile.id %}">
          <i class="fa fa-cog" aria-hidden="true"></i> Profile
        </a>
      </li>
      <li>
        <a href="{% url 'logout' %}">
          <i class="fa fa-sign-out" aria-hidden="true"></i> Logout
        </a>
      </li>
    </ul>
  </div>          
{% endblock %}


          

{% block dash_js %}

{% endblock %}
{% block js %}

{% endblock %}

app/templates/app/faq.html
{% extends 'app/base.html' %}

{% block style %}
    <style type="text/css">
        
        .faq {
        background: #FFFFFF;
        box-shadow: 0 2px 48px 0 rgba(0, 0, 0, 0.06);
        border-radius: 4px;
        }

        .faq .card {
        border: none;
        background: none;
        border-bottom: 1px dashed #CEE1F8;
        }

        .faq .card .card-header {
        padding: 0px;
        border: none;
        background: none;
        -webkit-transition: all 0.3s ease 0s;
        -moz-transition: all 0.3s ease 0s;
        -o-transition: all 0.3s ease 0s;
        transition: all 0.3s ease 0s;
        }

        .faq .card .card-header:hover {
            background: rgba(233, 30, 99, 0.1);
            padding-left: 10px;
        }
        .faq .card .card-header .faq-title {
        width: 100%;
        text-align: left;
        padding: 0px;
        padding-left: 30px;
        padding-right: 30px;
        font-weight: 400;
        font-size: 15px;
        letter-spacing: 1px;
        color: #3B566E;
        text-decoration: none !important;
        -webkit-transition: all 0.3s ease 0s;
        -moz-transition: all 0.3s ease 0s;
        -o-transition: all 0.3s ease 0s;
        transition: all 0.3s ease 0s;
        cursor: pointer;
        padding-top: 20px;
        padding-bottom: 20px;
        }

        .faq .card .card-header .faq-title .badge {
        display: inline-block;
        width: 20px;
        height: 20px;
        line-height: 14px;
        float: left;
        -webkit-border-radius: 100px;
        -moz-border-radius: 100px;
        border-radius: 100px;
        text-align: center;
        background: #00cc00;
        color: #fff;
        font-size: 12px;
        margin-right: 20px;
        }

        .faq .card .card-body {
        padding: 30px;
        padding-left: 35px;
        padding-bottom: 16px;
        font-weight: 400;
        font-size: 16px;
        color: #6F8BA4;
        line-height: 28px;
        letter-spacing: 1px;
        border-top: 1px solid #F3F8FF;
        }

        .faq .card .card-body p {
        margin-bottom: 14px;
        }

        @media (max-width: 991px) {
        .faq {
            margin-bottom: 30px;
        }
        .faq .card .card-header .faq-title {
            line-height: 26px;
            margin-top: 10px;
        }
        }
    </style>
{% endblock %}
{% block title %}FAQs - Arif Systems{% endblock %}

{% block content %}

    <section class="base-section">
        <div class="container">
          <div class="row">
                <!-- ***** FAQ Start ***** -->
                <div class="col-md-10 offset-md-1">

                    <div class="base-title text-center pb-1">
                        <h2>FAQs - Frequently Asked Questions</h2>
                    </div>
                </div>
                <div class="col-md-10 offset-md-1">
                    <div class="faq" id="accordion">
                        {% for item in list %}
                            <div class="card">
                                <div class="card-header" id="faqHeading-1">
                                    <div class="mb-0">
                                        <h5 class="faq-title" data-toggle="collapse" data-target="#faqCollapse-{{item.id}}" data-aria-expanded="true" data-aria-controls="faqCollapse-{{item.id}}">
                                            <span class="badge">{{ forloop.counter }}</span>{{item.question}}
                                        </h5>
                                    </div>
                                </div>
                                <div id='faqCollapse-{{item.id}}' class="collapse" aria-labelledby="faqHeading-{{item.id}}" data-parent="#accordion">
                                    <div class="card-body">
                                        <p>{{item.answer}}</p>
                                    </div>
                                    {% if  user.groups.all.0.name == "admin"  %}                                        <div>
                                            <a type="button" href="{% url 'edit_faq' pk=item.id %}" class="btn btn-success btn-block" style="color: white;"><i class="fa fa-plus" aria-hidden="true"></i>  Edit Faq</a>
                                            <a type="button" href="{% url 'faq_remove' pk=item.id %}" class="btn btn-success btn-block" style="color: white;"><i class="fa fa-plus" aria-hidden="true"></i>  Remove Faq</a>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                        
                        
                    </div>
                </div>
                </div>
            </div>
            </section>
{% endblock %}

app/templates/app/faq_detail.html
{% extends 'app/base.html' %}

{% block content %}
<ul class="list-group">
    <li class="list-group-item"><span class="pull-left"><strong class="">User:</strong></span> {{ salaryincometax.user_applicant.name }}</li>
    <li class="list-group-item"><span class="pull-left"><strong class="">Basic Salary: </strong></span> {{ salaryincometax.basic_salary }}</li>
    <li class="list-group-item"><span class="pull-left"><strong class="">Bonus: </strong></span> {{ salaryincometax.bonus }}</li>
    <li class="list-group-item"><span class="pull-left"><strong class="">Overtime Payment:</strong></span> {{ salaryincometax.overtime_payment }}</li>
    <li class="list-group-item"><span class="pull-left"><strong class="">Leave Pay: </strong></span> {{ salaryincometax.leave_pay }} </li>
    <li class="list-group-item"><span class="pull-left"><strong class="">Other Allowance: </strong></span> {{ salaryincometax.other_allowance }} </li>
    <li class="list-group-item"><span class="pull-left"><strong class="">Total Addition: </strong></span> {{ salaryincometax.total_addition }} </li>

    <li class="list-group-item"><span class="pull-right"><strong class="">Employees PF: </strong></span> {{ salaryincometax.employees_pf }}</li>
    <li class="list-group-item"><span class="pull-right"><strong class="">Citizen Investment Trust: </strong></span> {{ salaryincometax.citizen_investment_trust }}</li>
    <li class="list-group-item"><span class="pull-right"><strong class="">Life Insurance:</strong></span> {{ salaryincometax.life_insurance }}</li>
    <li class="list-group-item"><span class="pull-right"><strong class="">Medical Insurance: </strong></span> {{ salaryincometax.medical_insurance }} </li>
    <li class="list-group-item"><span class="pull-right"><strong class="">Other Exemptions: </strong></span> {{ salaryincometax.other_exemptions }} </li>
    <li class="list-group-item"><span class="pull-right"><strong class="">Total Deductions: </strong></span> {{ salaryincometax.total_deduction }} </li>
    <br>
    <br>
    <li class="list-group-item"><span class="pull-right"><strong class="">Taxable Income: </strong></span> {{ salaryincometax.total_taxable_income }} </li>
    <li class="list-group-item"><span class="pull-right"><strong class="">TDS: </strong></span> {{ salaryincometax.net_taxable_liability }} </li>
</ul>

<h1></h1>
<h2></h2>

<a class="btn btn-primary" href="{% url 'calculate_salary_tax' pk=salaryincometax.pk %}">
    <span>Calculate</span>
</a>

<a class="btn btn-warning" href="{% url 'edit_salary_income' pk=salaryincometax.pk %}">
    <span>Edit</span>
</a>

{% endblock %}

app/templates/app/faqs_confirm_delete.html
{% extends 'app/base.html' %}

{% block title %} Remove FAQs - Arif Systems{% endblock %}

{% block content %}

    <div class="row">
        <h1>Are you sure you want to delete this question: {{ faqs.question }} ?</h1>
    </div>
    
    <div class="row">
        <form method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Delete">
            <a href="{% url 'faq' %}">Cancel</a>
        </form>
    </div>
{% endblock %}

app/templates/app/faqs_form.html
{% extends 'app/base.html' %}
{% load bootstrap4 %}

{% block style %}
    <style type="text/css">
        
        .faq {
            background: #FFFFFF;
            box-shadow: 0 2px 48px 0 rgba(0, 0, 0, 0.06);
            border-radius: 4px;
        }

        .faq .card {
            border: none;
            background: none;
            border-bottom: 1px dashed #CEE1F8;
        }

        .faq .card .card-header {
            padding: 0px;
            border: none;
            background: none;
            -webkit-transition: all 0.3s ease 0s;
            -moz-transition: all 0.3s ease 0s;
            -o-transition: all 0.3s ease 0s;
            transition: all 0.3s ease 0s;
        }

        .faq .card .card-header:hover {
            background: rgba(233, 30, 99, 0.1);
            padding-left: 10px;
        }

        .faq .card .card-header .faq-title {
            width: 100%;
            text-align: left;
            padding: 0px;
            padding-left: 30px;
            padding-right: 30px;
            font-weight: 400;
            font-size: 15px;
            letter-spacing: 1px;
            color: #3B566E;
            text-decoration: none !important;
            -webkit-transition: all 0.3s ease 0s;
            -moz-transition: all 0.3s ease 0s;
            -o-transition: all 0.3s ease 0s;
            transition: all 0.3s ease 0s;
            cursor: pointer;
            padding-top: 20px;
            padding-bottom: 20px;
        }

        .faq .card .card-header .faq-title .badge {
            display: inline-block;
            width: 20px;
            height: 20px;
            line-height: 14px;
            float: left;
            -webkit-border-radius: 100px;
            -moz-border-radius: 100px;
            border-radius: 100px;
            text-align: center;
            background: #00cc00;
            color: #fff;
            font-size: 12px;
            margin-right: 20px;
        }

        .faq .card .card-body {
            padding: 30px;
            padding-left: 35px;
            padding-bottom: 16px;
            font-weight: 400;
            font-size: 16px;
            color: #6F8BA4;
            line-height: 28px;
            letter-spacing: 1px;
            border-top: 1px solid #F3F8FF;
        }

        .faq .card .card-body p {
            margin-bottom: 14px;
        }

        @media (max-width: 991px) {
            .faq {
                margin-bottom: 30px;
            }
            .faq .card .card-header .faq-title {
                line-height: 26px;
                margin-top: 10px;
            }
        }
    </style>
{% endblock %}

{% block title %}Create FAQ - Arif Systems{% endblock %}

{% block content %}
    <div class="container">
        <h2>FAQ</h2>
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% if not form.instance.pk %}
                <input type="submit" value=" Create FAQ " class="btn btn-primary">
            {% else %}
                <input type="submit" value=" Update FAQ" class="btn btn-primary">
            {% endif %}
        </form>
    </div>
{% endblock %}

app/templates/app/home.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Home - Arif Systems{% endblock %}
{% block style %}
<style>
    .content-container {
        margin-top: 0px;
    }
</style>
{% endblock %}
{% block header %}
  <!-- Header -->
  <header class="bg-light py-5">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-lg-12" style="text-align: center;">
        
            <img src="{% static "app/images/logo.png" %}"/>
          <h1 class="display-4 text-dark mt-5 mb-2">Arif Systems - Online Complaint Management</h1>
          <p class="lead mb-5 text-dark">Manage All your Tickets Online.</p>
          <a class="btn btn-success btn-lg center" href="{% url 'accounts:signup' %}">Get Started &raquo;</a>
        </div>
      </div>
    </div>
  </header>
{% endblock %}
{% block content %}



    <div class="row">
      <div class="col-md-8">
        <h2>Features</h2>
        <hr>
        <div class="row">
            <div class="col-md-4">
              <div class="card h-100">
                <img class="card-img-top" src="{% static 'app/images/ticket_mgmt.jpg' %}" alt="">
                <div class="card-body">
                  <h4 class="card-title">Manage Tickets</h4>
                  <p class="card-text">Create Tickets and View Status, all in one place.</p>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card h-100">
                <img class="card-img-top" src="{% static 'app/images/notification.png' %}"  alt="">
                <div class="card-body">
                  <h4 class="card-title">Notifications</h4>
                  <p class="card-text">Get Notified on any changes in Ticket Status.</p>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card h-100">
                <img class="card-img-top" src="{% static 'app/images/chat.png' %}" alt="">
                <div class="card-body">
                  <h4 class="card-title">Contact Engineers</h4>
                  <p class="card-text">Contact Engineers about Tickets or Report Issues.</p>
                </div>
              </div>
            </div>
          </div>        
      </div>
      <div class="col-md-4">
        <h2>Contact Us</h2>
        <hr>
        <address>
          <strong>Arif Systems</strong>
          <br>
        </address>
        <address>
          <abbr title="Phone">P:</abbr>
          (123) 456-7890
          <br>
          <abbr title="Email">E:</abbr>
          <a href="mailto:#">info@arifsystems.org</a>
        </address>
      </div>
    </div>
    <!-- /.row -->

   
    <!-- /.row -->


{% endblock %}