adm/urls.py
from django.urls import path, include

from adm import views

app_name='admin_app'
urlpatterns = [
    # path('', views.index, name='dashboard'),
    path('dashboard/', views.index, name='admin_dashboard'),
    path('dashboard/tickets/', views.tickets, name='admin_tickets'),
    path('dashboard/tickets/create_new_ticket/', views.create_new_ticket, name='create_new_ticket'),
    path('tickets/assign_tickets/<int:pk>', views.assign_tickets, name='assign_tickets'),
    path('dashboard/reports/', views.reports, name='admin_reports'),
    # path('pie-chart/', views.pie_chart, name='pie-chart'),
    path('report-form-chart/', views.report_form_data, name='report-form-chart'),
    path('report-form/', views.report_form, name='report-form'),
]

engineer/urls.py
from django.urls import path

from engineer import views

app_name = "engineer_app"
urlpatterns = [
    path('', views.index, name='dashboard'),
    path('dashboard/', views.index, name='dashboard'),
    path('dashboard/ticket_list/', views.ticket_list, name='eng_ticket_list'),
    path('confirmation/', views.start_working, name='start_working_confirm'),
    path('confirmation/close_tkt', views.close_ticket, name='close_ticket'),
    path('confirmation/take_tkt', views.take_ticket, name='take_ticket'),
    path('dashboard/engineers_list', views.engineers_list, name='engineers_list'),
    path('change_active_status/<int:pk>', views.change_active_status, name='change_active_status'),
    path('report-form-chart-eng/', views.report_form_data_eng, name='report-form-chart-eng'),
]

tkt_mgmt/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('app/', include('app.urls')),
    path('', include('usr.urls')),
    path('dashboard/', include('usr.urls')),
    path('', include('adm.urls')),
    path('dashboard/', include('adm.urls')),
    path('', include('django.contrib.auth.urls')),
    path('dashboard/', include('engineer.urls')),
    path('', include('engineer.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),

]

usr/urls.py
from django.urls import path
from django.conf.urls import url
from usr import views

app_name = "user_tickets"
urlpatterns = [
    path('', views.index, name='dashboard'),
    path('dashboard/', views.index, name='dashboard'),
    path('dashboard/my_tickets/', views.my_tickets, name='my_tickets'),
    path('dashboard/my_tickets/file_a_ticket/', views.file_a_ticket, name='file_a_ticket'),
    path('ticket_details/<int:pk>', views.TicketDetailView.as_view(), name='ticket_details'),
    path('view_history/', views.view_history, name='view_history'),
]

adm/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

adm/forms.py
from django import forms
from app.models import Tickets
from bootstrap_datepicker_plus import DatePickerInput, TimePickerInput, DateTimePickerInput, MonthPickerInput, YearPickerInput

class TicketForm(forms.ModelForm):
    class Meta:
        model = Tickets
        fields = ["ticket_id","issue_type","created_at", "description", "finish_date","user", "priority","assigned_to"]
        widgets = {
            'finish_date': DatePickerInput(),
        }
        labels={
            "finish_date":"Due By",
            "assigned_to":"Assign To",
        }


class TicketAssignForm(forms.ModelForm):
    class Meta:
        model = Tickets
        fields = ["finish_date", "priority","assigned_to"]
        widgets = {
            'finish_date': DatePickerInput(),
        }
        labels={
            "finish_date":"Due By",
            "assigned_to":"Assign To",
        }


# form for report
import datetime
class ReportForm(forms.Form):
    username = forms.CharField(label="Username", max_length=100)
    date_from = forms.DateTimeField(initial=datetime.date.today().replace(day=1), widget=DatePickerInput(format='%m/%d/%Y'))
    date_to = forms.DateTimeField(initial=datetime.date.today, widget=DatePickerInput(format='%m/%d/%Y'))

adm/views.py
import datetime

from app import notification
from app.models import (Status, Tickets,
                        TicketStatusHistory)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.views.generic import ListView, UpdateView
import json
from django.core.serializers import serialize
from django.db.models import Sum
from django.http import JsonResponse

from .forms import TicketAssignForm, TicketForm
import adm.admin_reports as admin_reports

# Create your views here.
@login_required(login_url='/login/')
def index(response):
    new_tickets = Tickets.objects.filter((Q(is_closed=None) | Q(is_closed = False)),assigned_to=None).count()
    overdue = Tickets.objects.filter((Q(is_closed=None) | Q(is_closed = False)), finish_date__lt = datetime.datetime.today()).count()
    complete = Tickets.objects.filter(status=Status.objects.get(status='Complete')).count()
    # data = (['Ticket Status','Number of Tickets'],['New Tickets',new_tickets],['Assigned Tickets',assigned],['Inprogress',working_on],['Completed',complete])
    data = admin_reports.ticket_counts
    line_data = admin_reports.ticketStatus
    return render(response, 'adm/dashboard.html',{'new':new_tickets,'overdue':overdue,'complete':complete, 'data':data, 'line_data':line_data})

@login_required(login_url='/login/')
def tickets(response):
    new_tickets = Tickets.objects.filter((Q(is_closed=None) | Q(is_closed = False)),assigned_to=None).order_by('ticket_id')
    assigned = Tickets.objects.filter(status=Status.objects.get(status='Assigned'))
    working_on = Tickets.objects.filter(status=Status.objects.get(status='Inprogress'))
    complete = Tickets.objects.filter(status=Status.objects.get(status='Complete'))

    args = {
        'new_tickets':new_tickets,
        'assigned':assigned,
        'working_on':working_on,
        'complete':complete
    }
    return render(response, 'adm/admin_tickets.html',args)


@login_required(login_url='/login/')
def create_new_ticket(response):
    if response.method == "POST":
        form = TicketForm(response.POST or None)
        if form.is_valid():
            tickets = form.save(commit=False)
            tickets.user = response.user
            tickets.save()
            return redirect('/dashboard/tickets')
    else:
        form=TicketForm()
    args = {'form': form}

    return render(response, 'adm/create_new_ticket.html',args)

@login_required(login_url='/login/')
def assign_tickets(response, pk):
    ticket = Tickets.objects.get(ticket_id=pk)
    userInfo = User.objects.get(username=ticket.user)
    form = TicketAssignForm(response.POST or None, instance=ticket)

    if response.method == "POST":
        if form.is_valid():
            tickets = form.save(commit=False)
            ticket.priority = tickets.priority
            ticket.finish_date = tickets.finish_date
            ticket.assigned_to = tickets.assigned_to
            ticket.assigned_at = datetime.datetime.now()
            ticket.status = Status.objects.get(status='Assigned')
            ticket.save()

            notification.change_status(ticket, response.user, 'Ticket is Assigned')
                        
            return redirect('/dashboard/tickets')

    args = {'form': form,'userInfo':userInfo, 'ticket':ticket}

    return render(response, 'adm/assign_tickets.html',args)


def reports(response):
    data = admin_reports.ticketStatus
    args={
        'data':data
    }
    return render(response,'adm/report.html', args)
# for report form
from .forms import ReportForm
from django.http import HttpResponseRedirect

def report_form(response):
    return render(response, 'adm/report_form.html')

def report_form_data(request):
    user_group = [group.name for group in request.user.groups.all()]

    if request.method == 'POST':
        form = ReportForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            date_from = form.cleaned_data['date_from']
            date_to = form.cleaned_data['date_to']
            print(username, date_from, date_to)
            print(type(date_from))

            labels = ["Completed", "In Progress", "Overdue"]
            data = []
            if 'admin' in user_group:
                engineer_id = User.objects.get(username=username).id
            elif 'engineer' in user_group:
                engineer_id = request.user.id
            else:
                print("not accessible")
            
            queryset = Tickets.objects.filter(assigned_to__exact=engineer_id)

            complete_queryset = queryset.filter(status__status='Complete')
            no_of_completed_tickets = find_no(complete_queryset, date_from, date_to)
            print("no of completed tickets", no_of_completed_tickets)
            data.append(no_of_completed_tickets)

            inprogress_queryset = queryset.filter(status__status='Inprogress')
            no_of_inprogress_tickets = find_no(inprogress_queryset, date_from, date_to)
            print("no of inprogress tickets", no_of_inprogress_tickets)
            data.append(no_of_inprogress_tickets)

            overdue_queryset = queryset.filter(status__status='Inprogress')
            no_of_overdue_tickets = find_overdue_no(overdue_queryset, date_from, date_to)
            print("no of overdue tickets", no_of_overdue_tickets)
            data.append(no_of_overdue_tickets)

            return render(request, 'adm/pie_chart.html', {
                'labels': labels,
                'data': data,
                'username': username,
    })

    else:
        form = ReportForm()
    if 'admin' in user_group:
        return render(request, 'adm/report_form.html', {'form': form})
    else:
        return render(request, 'engineer/report_form_eng.html', {'form': form})
    

def find_no(queryset, date_from, date_to):
    ticket_ids = [tkt_id.pk for tkt_id in queryset]
    count = 0
    for ticket_id in ticket_ids:
        match_val = TicketStatusHistory.objects.filter(ticket_id=ticket_id)
        match_val = match_val.order_by('-change_time')[0]
        if date_from <= match_val.change_time and match_val.change_time <= date_to:
            count = count + 1
    return count

def find_overdue_no(queryset, date_from, date_to):
    ticket_ids = [tkt_id.pk for tkt_id in queryset]
    count = 0
    for ticket_id in ticket_ids:
        match_val = TicketStatusHistory.objects.filter(ticket_id=ticket_id)
        match_val = match_val.order_by('-change_time')[0]
        finish_date = Tickets.objects.get(pk=ticket_id).finish_date
        if date_from <= match_val.change_time and match_val.change_time <= date_to and finish_date < datetime.date.today():
            count = count + 1
    return count

adm/templates/adm/admin_sidenav.html
{% extends "app/dash_base.html" %}

{% block sidnav %}
    <li>
        <a href="/dashboard/tickets/">
        <i class="fa fa-ticket" aria-hidden="true"></i> Tickets
        </a>
    </li>
    <li>
        <a href="{% url 'engineer_app:engineers_list' %}">
          <i class="fa fa-user-md" aria-hidden="true"></i> Engineers
        </a>
    </li>
    <!-- <li>
        <a href="#">
          <i class="fa fa-users" aria-hidden="true"></i> Users
        </a>
    </li> -->
    <li>
        
      <a href="{% url 'create_faq' %}">
        <i class="fa fa-question-circle" aria-hidden="true"></i> Create FAQs
      </a>
  </li>
    <li>
        <a href="/dashboard/report-form-chart/">
          <i class="fa fa-bar-chart" aria-hidden="true"></i> Reports
        </a>
    </li>
{% endblock %}

adm/templates/adm/admin_tickets.html
{% extends base_template_name %}
{% load static %}

{% block title %}Tickets{% endblock %}

{% block style %}
<link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet">

{% endblock %}


{% block content%}
{% include "app/_modal.html" %}
{% include "app/chat.html" %}
<div class="container">
    <div class="row">
        <div class="col col-md-8">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                  <a class="nav-link active" data-toggle="tab" href="#new">New Tickets</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#assigned">Assigned</a>
                </li>  
                <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#working">Inprogress</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#complete">Complete</a>
                </li>
            </ul>
        </div>
        <div class="col">
            <h3>Tickets list</h3>
          </div>
    
    </div>
<!-- Modal -->
    <hr />
    <!-- Tab panes -->
    <div class="tab-content">
        <div class="tab-pane container active" id="new">
            <table  id="example" class="table table-striped table-bordered tkt_tbl" style="width:100%">
                <thead>
                    <tr>
                        <th>Ticket No.</th>
                        <th>Issue</th>
                        <th>Issued By</th>
                        <th>Due Date</th>
                        <th>Created At</th>
                        <th>Status</th>
                        <th>Priority</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in new_tickets %}
                    <tr style="background-color: {% if item.is_past_due %}red{%endif%};">
                        <td data-order="{{ item.ticket_id }}">#{{ item.ticket_id }} </td>
                        <td>{{ item.issue_type }} </td>
                        <td>{{ item.user.username }} </td>
                        <td>{{ item.finish_date|date:'Y-m-d' }} </td>
                        <td>{{ item.created_at|date:'Y-m-d H:i' }} </td>
                        <td>
                            {% if item.status %}
                                {{ item.status.status }}
                            {% else %}
                                Pending
                            {% endif %}
                        </td>
                        <td style="background-color: {{item.priority_color}};" data-order="{{ item.priority_order }}">{{ item.priority }} </td>
                        <td>
                            <a type="button"  href="{% url 'admin_app:assign_tickets' item.ticket_id %}" class="btn btn-success"> <i class="fa fa-user-plus" aria-hidden="true"></i> </a>
                            <a type="button" data-id="{% url 'user_tickets:ticket_details' item.ticket_id %}" class="viewtkt btn btn-primary"> <i class="fa fa-eye" aria-hidden="true"></i>  </a>
                            <a type="button" data-toggle="modal" data-id="{{ item.ticket_id }}" data-target="#chatModal" class="chat btn btn-success"> <i class="fa fa-comments" aria-hidden="true"></i>  </a>
                        </td>
                    </tr>
                        {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="tab-pane container fade" id="assigned">
            <table  id="assigned_tbl" class="table table-striped table-bordered tkt_tbl" style="width:100%">
                <thead>
                    <tr>
                        <th>Ticket No.</th>
                        <th>Issue</th>
                        <th>Issued By</th>
                        <th>Due Date</th>
                        <th>Created At</th>
                        <th>Assigned To</th>
                        <th>Priority</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in assigned %}
                    <tr style="background-color: {% if item.is_past_due %}red{%endif%};">
                        <td data-order="{{ item.ticket_id }}">#{{ item.ticket_id }} </td>
                        <td>{{ item.issue_type }} </td>
                        <td>{{ item.user.username }} </td>
                        <td>{{ item.finish_date|date:'Y-m-d' }} </td>
                        <td>{{ item.created_at|date:'Y-m-d H:i' }} </td>
                        <td>
                            {{ item.assigned_to }}
                        </td>
                        <td style="background-color: {{item.priority_color}};" data-order="{{ item.priority_order }}">{{ item.priority }} </td>
                        <td>
                            <a type="button" data-id="{% url 'user_tickets:ticket_details' item.ticket_id %}" class="viewtkt btn btn-primary"> <i class="fa fa-eye" aria-hidden="true"></i>  </a>
                            <a type="button" data-toggle="modal" data-id="{{ item.ticket_id }}" data-target="#chatModal" class="chat btn btn-success"> <i class="fa fa-comments" aria-hidden="true"></i>  </a>
                        </td>
                    </tr>
                        {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="tab-pane container fade" id="working">
            <table  id="working_tbl" class="table table-striped table-bordered tkt_tbl" style="width:100%">
                <thead>
                    <tr>
                        <th>Ticket No.</th>
                        <th>Issue</th>
                        <th>Issued By</th>
                        <th>Due Date</th>
                        <th>Created At</th>
                        <th>Assigned To</th>
                        <th>Priority</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in working_on %}
                    <tr style="background-color: {% if item.is_past_due %}red{%endif%};">
                        <td data-order="{{ item.ticket_id }}">#{{ item.ticket_id }} </td>
                        <td>{{ item.issue_type }} </td>
                        <td>{{ item.user.username }} </td>
                        <td>{{ item.finish_date|date:'Y-m-d' }} </td>
                        <td>{{ item.created_at|date:'Y-m-d H:i' }} </td>
                        <td>
                            {{ item.assigned_to }}
                        </td>
                        <td style="background-color: {{item.priority_color}};" data-order="{{ item.priority_order }}">{{ item.priority }} </td>
                        <td>
                            <a type="button" data-id="{% url 'user_tickets:ticket_details' item.ticket_id %}" class="viewtkt btn btn-primary"> <i class="fa fa-eye" aria-hidden="true"></i>  </a>
                            <a type="button" data-toggle="modal" data-id="{{ item.ticket_id }}" data-target="#chatModal" class="chat btn btn-success"> <i class="fa fa-comments" aria-hidden="true"></i>  </a>
                        </td>
                    </tr>
                        {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="tab-pane container fade" id="complete">
            <table  id="complete_tbl" class="table table-striped table-bordered tkt_tbl" style="width:100%">
                <thead>
                    <tr>
                        <th>Ticket No.</th>
                        <th>Issue</th>
                        <th>Issued By</th>
                        <th>Due Date</th>
                        <th>Created At</th>
                        <th>Assigned To</th>
                        <th>Priority</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in complete %}
                    <tr>
                        <td data-order="{{ item.ticket_id }}">#{{ item.ticket_id }} </td>
                        <td>{{ item.issue_type }} </td>
                        <td>{{ item.user.username }} </td>
                        <td>{{ item.finish_date|date:'Y-m-d' }} </td>
                        <td>{{ item.created_at|date:'Y-m-d H:i' }} </td>
                        <td>
                            {{ item.assigned_to }}
                        </td>
                        <td style="background-color: {{item.priority_color}};" data-order="{{ item.priority_order }}">{{ item.priority }} </td>
                        <td>
                            <a type="button" data-id="{% url 'user_tickets:ticket_details' item.ticket_id %}" class="viewtkt btn btn-primary"> <i class="fa fa-eye" aria-hidden="true"></i>  </a>
                        </td>
                    </tr>
                        {% endfor %}
                </tbody>
            </table>
        </div>
        
    </div>

{% endblock %}

{% block js %}
<script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>
<script src="{% static 'js/chat.js' %}"></script>
<script>
    $(document).ready(function() {
        $('.viewtkt').on('click', function(){
            $(this).modalForm({
                formURL: $(this).data('id')
            });
        });
        $('.tkt_tbl').DataTable();

    } );
</script>
{% endblock %}

adm/templates/adm/assign_tickets.html
{% extends base_template_name %}
{% block title %}Assign Ticket{% endblock %}


{% load crispy_forms_tags %}
{% block content %}
<div class="col-md-10">

  <div class="base-title text-center pb-1">
      <h2>Assign Ticket</h2>
  </div>
</div>
<div class="container col-md-6">
    <div class="well">
      <form class="form-horizontal">
        <div class="form-group">
          <label class="control-label col-sm-3">Ticket ID:</label>
             <label class="col-sm-2">#{{ ticket.ticket_id }}</label>
             <label class="control-label col-sm-3">Issued By:</label>
             <label class="col-sm-3">{{ userInfo.username }}</label> 
        </div>
        <div class="form-group">
          <label class="control-label col-sm-3">Issue:</label>
            <label>{{ ticket.issue_type }}</label>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-3">Issued At:</label>
            <label>{{ ticket.created_at }}</label>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-3">Email:</label>
             <label>{{ userInfo.email }}</label>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-3">Description:</label>
             <label>{{ ticket.description }}</label>
        </div>
  
      </form>
    </div>
  <form method="POST" >
    {% csrf_token %}
  <div class="form-row">
    <div class="form-group  col-md-6">
      {{ form.finish_date|as_crispy_field }}
      {{ form.assigned_to|as_crispy_field }}
    </div>
    <div class="form-group col-md-6">
      {{ form.priority|as_crispy_field }}
    </div>
  </div>
  <div class="form-row">
    <div class="form-group  col-md-6">
      <button id="btn_submit" type="submit" class="btn btn-success btn-block"> <i class="fa fa-save" aria-hidden="true"></i>  Assign</button>
    </div>
    <div class="form-group col-md-6">
      <a id="btn_cancel" type="button" href="/dashboard/tickets" class="btn btn-danger btn-block" style="color: white;"><i class="fa fa-times-circle-o" aria-hidden="true"></i>  Cancel</a>
    </div>
  </div>
</form>
</div>

{% endblock %}
{% block js %}
{{ form.media }} 
<script>
  $(function(){
      $('form').on('submit', function(e){
        let overlay = document.getElementsByClassName('loading-overlay')[0]
        overlay.classList.toggle('is-active');  
      });
  })
</script>
{% endblock %}

adm/templates/adm/create_new_ticket.html
{% extends base_template_name %}
{% block title %}Create New Ticket{% endblock %}


{% load crispy_forms_tags %}
{% block content%}
<div class="col-md-10">

  <div class="base-title text-center pb-1">
      <h2>Create New Ticket</h2>
  </div>
</div>
<div class="container col-md-6">
  <form method="POST" >
    {% csrf_token %}
  <div class="form-row">
    <div class="form-group  col-md-6">
      {{ form.issue_type|as_crispy_field }}
      {{ form.finish_date|as_crispy_field }}
      {{ form.priority|as_crispy_field }}
      {{ form.assigned_to|as_crispy_field }}
    </div>
    <div class="form-group col-md-6">
      {{ form.description|as_crispy_field }}
    </div>
  </div>
  <div class="form-row">
    <div class="form-group  col-md-6">
      <button type="submit" class="btn btn-success btn-block"> <i class="fa fa-save" aria-hidden="true"></i>  Create</button>
    </div>
    <div class="form-group col-md-6">
      <a type="button" href="/dashboard/tickets" class="btn btn-danger btn-block" style="color: white;"><i class="fa fa-times-circle-o" aria-hidden="true"></i>  Cancel</a>
    </div>
  </div>
</form>
</div>

{% endblock %}
{% block js %}
{{ form.media }} 
{% endblock %}

adm/templates/adm/dashboard.html
{% extends base_template_name %}
{% load static %}

{% block title %}Dashboard{% endblock %}



{% block content %}
<div class="container">
<div class="row">
    <div class="col-xl-4 col-sm-6 mb-4 ">
      <div class="card text-white bg-primary o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fa fa-fw fa-plus"></i>
          </div>
          <div class="mr-5">{{new}} New Tickets!</div>
        </div>
        <a class="card-footer text-white clearfix small z-1" href="{% url 'admin_app:admin_tickets' %}">
          <span class="float-left">View Details</span>
          <span class="float-right">
            <i class="fa fa-angle-right"></i>
          </span>
        </a>
      </div>
    </div>
    <div class="col-xl-4 col-sm-6 mb-4">
      <div class="card text-white bg-danger o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fa fa-fw fa-list"></i>
          </div>
          <div class="mr-5">{{overdue}} Overdue Tickets</div>
        </div>
        <a class="card-footer text-white clearfix small z-1" href="{% url 'admin_app:admin_tickets' %}">
          <span class="float-left">View Details</span>
          <span class="float-right">
            <i class="fa fa-angle-right"></i>
          </span>
        </a>
      </div>
    </div>
    <div class="col-xl-4 col-sm-6 mb-4">
      <div class="card text-white bg-success o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fa fa-fw fa-check"></i>
          </div>
          <div class="mr-5">{{complete}} Completed Tickets!</div>
        </div>
        <a class="card-footer text-white clearfix small z-1" href="{% url 'admin_app:admin_tickets' %}">
          <span class="float-left">View Details</span>
          <span class="float-right">
            <i class="fa fa-angle-right"></i>
          </span>
        </a>
      </div>
    </div>
  </div>
<div class="row" style="margin-top: 10px;">
    <div class="col col-md-6" id="">
        <h5>Notifications</h5>
        <table class="table">
            <thead class="thead-dark">
                <th>Title</th>
                <th>Message</th>
            </thead>
            <tbody id='notification'></tbody>
        </table>
    </div>
  <div class="col col-md-4" id="chart_div">
  </div>
  

</div>
<div class="row" style="margin-top: 5px;">
    <div class="col col-md-12" id="line_chart_div">
    </div>
</div>
</div>

{% endblock %}
{% block js %}
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
    $(document).ready(function() {
        htmls = '<td colspan="2">There is no new notifications</td>';

        $('#notification').html(htmls);
        linechart();
        } );
    google.load('visualization', '1.0', {'packages':['corechart']});
    google.setOnLoadCallback(drawChart);
    function drawChart() {
   
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Status');
        data.addColumn('number');
        data.addRows({{ data|safe }});
        var colors = [];
        var colorMap = {
            // should contain a map of category -> color for every category
            'Assigned': '#ffcc00',
            'New Tickets': '#592df7',
            'Inprogress': '#66ff33',
            'Cancelled': '#e63b6f',
            "Complete": '#19c362'
        }
        for (var i = 0; i < data.getNumberOfRows(); i++) {
            colors.push(colorMap[data.getValue(i, 0)]);
        }
    var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
    chart.draw(data, {width: 400, height: 240, title: "Ticket Status",colors: colors});
    }

    function linechart(){
        google.charts.load('current', {packages: ['corechart', 'corechart']});
        google.charts.setOnLoadCallback(drawLogScales);

        function drawLogScales() {
            var data = new google.visualization.DataTable();
                var datas ={{line_data|safe}};
            data.addColumn('date', 'Date');
            data.addColumn('number', 'Created');
            data.addColumn('number', 'Completed');
            debugger
            //   data.addColumn('number', 'Cats');
            datas.forEach(element => {
                d = element[0];
                if(d!= null){
                    data.addRow([new Date(d),element[1], element[2]])
                }
            });

            var options = {
                title: 'Status of Tickets on daily basis',
                width: 900,
                height: 500,
                hAxis: {
                    format: 'M/d/yy',
                    gridlines: {count: 15}
                },
                vAxis: {
                    gridlines: {color: 'none'},
                    minValue: 0
                },
                colors: ['blue', 'green']
                };

            var chart = new google.visualization.LineChart(document.getElementById('line_chart_div'));
            var results = google.visualization.data.group(data, [0], [{'column': 1, 'aggregation': google.visualization.data.sum, 'type': 'number'},{'column': 2, 'aggregation': google.visualization.data.sum, 'type': 'number'}])
            chart.draw(results, options);
            var button = document.getElementById('change');

                button.onclick = function () {

                // If the format option matches, change it to the new option,
                // if not, reset it to the original format.
                options.hAxis.format === 'M/d/yy' ?
                options.hAxis.format = 'MMM dd, yyyy' :
                options.hAxis.format = 'M/d/yy';

                chart.draw(data, options);
                };
            }
    }
    </script>
{% endblock %}

adm/templates/adm/report.html
{% extends base_template_name %}
{% load static %}
{% block title %}Tickets{% endblock %}
{% block style %}
<link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet">

{% endblock %}

{% block content%}
<div id="chart_div"></div>
{% endblock %}


{% block js %}
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script>
    $(document).ready(function() {
        

    } );
</script>
{% endblock %}

adm/templates/adm/report_form.html
{% extends base_template_name %}
{% load bootstrap4 %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Generate Report" class="btn btn-primary btn-block">
    </form>
{% endblock %}

{% block js %}
    {{ form.media }} 
{% endblock %}